on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.2

    - run: pip install -r requirements.txt pyinstaller
    - run: ./build.sh
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: dist/restart_uap -v
    - uses: actions/upload-artifact@v3
      with:
        name: restart_uap
        path: dist/restart_uap
        retention-days: 21
